
project_id = "stwogjmlokgpkdliizxf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[functions.create-admin-user]
verify_jwt = true

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
port = 54325

[realtime]
port = 54326

[storage]
port = 54327
