// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stwogjmlokgpkdliizxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0d29nam1sb2tncGtkbGlpenhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzcxOTUsImV4cCI6MjA2MjExMzE5NX0.hoeRRqbOxfU0Er1I1KqlxycVkNlUOOjiSK40KygclPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);